## Project 3 - Part 2

Author: Qichun Yu

### Question 1

a) Import gensim and logging . Using the scikit documentation give a short description of both gensim and logging. You may use the following code snippet.

In [1]:
import gensim, logging

C:\Users\jacks\anaconda3\envs\UL\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [2]:
logging.basicConfig(format='%(asctime)s :%(levelname)s : %(message)s', level=logging.INFO)

b) Load the Google w2v model. You may have to locate this file on the internet.

In [3]:
gmodel = gensim.models.KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True)

2022-10-30 00:26:36,100 :INFO : loading projection weights from GoogleNews-vectors-negative300.bin
2022-10-30 00:26:59,026 :INFO : KeyedVectors lifecycle event {'msg': 'loaded (3000000, 300) matrix of type float32 from GoogleNews-vectors-negative300.bin', 'binary': True, 'encoding': 'utf8', 'datetime': '2022-10-30T00:26:59.025831', 'gensim': '4.0.1', 'python': '3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)]', 'platform': 'Windows-10-10.0.19041-SP0', 'event': 'load_word2vec_format'}


c) Display the vector for the following words.
<ol>
    <li>‘cat’</li>
    <li>‘dog’</li>
    <li>‘spatula’</li>
</ol>

In [4]:
# Display Cat
gmodel['cat']

array([ 0.0123291 ,  0.20410156, -0.28515625,  0.21679688,  0.11816406,
        0.08300781,  0.04980469, -0.00952148,  0.22070312, -0.12597656,
        0.08056641, -0.5859375 , -0.00445557, -0.296875  , -0.01312256,
       -0.08349609,  0.05053711,  0.15136719, -0.44921875, -0.0135498 ,
        0.21484375, -0.14746094,  0.22460938, -0.125     , -0.09716797,
        0.24902344, -0.2890625 ,  0.36523438,  0.41210938, -0.0859375 ,
       -0.07861328, -0.19726562, -0.09082031, -0.14160156, -0.10253906,
        0.13085938, -0.00346375,  0.07226562,  0.04418945,  0.34570312,
        0.07470703, -0.11230469,  0.06738281,  0.11230469,  0.01977539,
       -0.12353516,  0.20996094, -0.07226562, -0.02783203,  0.05541992,
       -0.33398438,  0.08544922,  0.34375   ,  0.13964844,  0.04931641,
       -0.13476562,  0.16308594, -0.37304688,  0.39648438,  0.10693359,
        0.22167969,  0.21289062, -0.08984375,  0.20703125,  0.08935547,
       -0.08251953,  0.05957031,  0.10205078, -0.19238281, -0.09

In [5]:
# Display Dog
gmodel['dog']

array([ 5.12695312e-02, -2.23388672e-02, -1.72851562e-01,  1.61132812e-01,
       -8.44726562e-02,  5.73730469e-02,  5.85937500e-02, -8.25195312e-02,
       -1.53808594e-02, -6.34765625e-02,  1.79687500e-01, -4.23828125e-01,
       -2.25830078e-02, -1.66015625e-01, -2.51464844e-02,  1.07421875e-01,
       -1.99218750e-01,  1.59179688e-01, -1.87500000e-01, -1.20117188e-01,
        1.55273438e-01, -9.91210938e-02,  1.42578125e-01, -1.64062500e-01,
       -8.93554688e-02,  2.00195312e-01, -1.49414062e-01,  3.20312500e-01,
        3.28125000e-01,  2.44140625e-02, -9.71679688e-02, -8.20312500e-02,
       -3.63769531e-02, -8.59375000e-02, -9.86328125e-02,  7.78198242e-03,
       -1.34277344e-02,  5.27343750e-02,  1.48437500e-01,  3.33984375e-01,
        1.66015625e-02, -2.12890625e-01, -1.50756836e-02,  5.24902344e-02,
       -1.07421875e-01, -8.88671875e-02,  2.49023438e-01, -7.03125000e-02,
       -1.59912109e-02,  7.56835938e-02, -7.03125000e-02,  1.19140625e-01,
        2.29492188e-01,  

In [6]:
# Display Spatula
gmodel['spatula']

array([-0.19140625, -0.04296875,  0.27539062,  0.00488281, -0.3203125 ,
        0.08203125,  0.05566406, -0.03613281, -0.31445312,  0.10693359,
       -0.359375  ,  0.29882812,  0.02331543,  0.05517578, -0.140625  ,
        0.1953125 , -0.23632812, -0.22167969, -0.06542969, -0.3359375 ,
        0.25195312, -0.09326172,  0.54296875,  0.11328125, -0.28710938,
       -0.12011719, -0.11181641,  0.20996094, -0.33203125,  0.30273438,
       -0.3359375 , -0.12255859,  0.12890625, -0.28515625, -0.04223633,
        0.25585938,  0.3203125 ,  0.07177734,  0.19042969, -0.01379395,
        0.16992188, -0.22460938,  0.5078125 ,  0.08398438, -0.07519531,
       -0.06396484,  0.05371094,  0.34570312,  0.46289062, -0.16699219,
       -0.30664062,  0.15234375, -0.09765625, -0.26171875, -0.14160156,
        0.2265625 ,  0.49609375, -0.10791016, -0.08447266,  0.234375  ,
        0.04931641, -0.07128906,  0.05273438, -0.11914062,  0.09814453,
        0.11181641, -0.13574219, -0.46875   ,  0.26171875,  0.12

d) Output the similarity scores for the following pairs.
<ol>
    <li>‘dog’ , ‘cat’</li>
    <li>‘dog’ , ‘spatula’</li>
</ol>

In [7]:
# Similarity scores for 'dog' and 'cat'
gmodel.similarity('dog','cat')

0.76094574

In [8]:
# Similarity scores for 'dog' and 'spatula'
gmodel.similarity('dog', 'spatula')

0.17059729

### Question 2

a) Use the following code to train your model. We will use doc2vec as we wan a vector for each document.

In [9]:
from gensim.models.doc2vec import TaggedDocument
from gensim.models import Doc2Vec

b) Using the scikit documentation give a brief description of the genism library, and the TaggedDocument class.

Genism library is free open source Python library for natural language processing(NLP). The library includes topic modelling, document indexing and similarity retrieval with large corpora. 

c) Incorporate the following utility function into your code.

In [10]:
def extract_words(sent):
    sent = sent.lower()
    sent = re.sub(r'<[^>]+>', ' ', sent) 
    sent = re.sub(r'(\w)\'(\w)', '\1\2', sent) 
    sent = re.sub(r'\W', ' ', sent) 
    sent = re.sub(r'\s+', ' ', sent)
    sent = sent.strip()
    return sent.split()

d) Describe exactly what the utility function is doing.

The utility takes sent as input. In the first line of code change the words to lowercase. The second to the fifth line are using the re.sub(), which is a function in the built-in re module to handle regular expressions. The codes remove any HTML tags, apostrophes, punctuation, and repeated spaces from the sent. After that, the function uses the strip() method to remove any spaces at the beginning and at the end of the string. In the end, it returns and uses the split() method to spit a string into a list so that each word will be separated and stored individually into a list. 

### Question 3

a) Use the code snippet in your worksheet. You will need to access the files in the comments of the codes.

In [11]:
import re
import os
unsup_sentences = []

for dirname in ["train/pos", "train/neg", "train/unsup", "test/pos", "test/neg"]:
    for fname in sorted(os.listdir("aclimdb/" + dirname)):
        if fname[-4:] == ".txt":
            with open("aclimdb/" + dirname + "/" + fname, encoding='UTF-8') as f:
                sent = f.read()
                words = extract_words(sent)
                unsup_sentences.append(TaggedDocument(words,[dirname + "/" + fname]))
print(len(unsup_sentences))

for dirname in ["review_polarity/txt_sentoken/pos","review_polarity/txt_sentoken/neg"]:
    for fname in sorted(os.listdir(dirname)):
        if fname[-4:] == ".txt":
             with open(dirname + "/" + fname, encoding='UTF-8') as f:
                    for i, sent in enumerate(f):
                        words = extract_words(sent)
                        unsup_sentences.append(TaggedDocument(words,["%s/%s-%d" % (dirname, fname,i)]))
print(len(unsup_sentences))

with open("stanfordSentimentTreebank/original_rt_snippets.txt", encoding = 'UTF-8') as f:
    for i, line in enumerate(f):
        words = extract_words(line)
        unsup_sentences.append(TaggedDocument(words,["rt-%d" %i]))

print(len(unsup_sentences))

100000
164720
175325


b) Explain the function of the code in part(a). Explain each loop.

We first create an empty list called unsup_sentences. The first for loop opens all the txt files within the aclImdb folder, which contains IMDB review data. The aclImdb dataset includes 50,000 labelled reviews (25,000 for the training dataset and 25,000 for the testing dataset) and 50,000 unlabelled movie reviews. As we can see the len of the unsup_sentences list is 100,000. The TaggedDocument helps to represent a document along with a tag. We pass the words from the txt files as the input document with the tag that has the information of dirname(indicates whether the text is from training or testing) and fname(name of the file). 

The second for loop opens all the txt files within the review_polarity folder, which also contains movie review data but the datasets come from cornell.edu. The dataset includes 67,720 review data and is split into neg(negative) and pos(positive). The for loop is doing similar things to the first one to use TaggedDocument to store text with a tag. 

The third for loop is a simple loop that reads the data file oriiginal_rt_snippets.txt from Rotten Tomatoes. The files contain 10,605 processed snippets from the original pool of Rotten Tomatoes. The loop also uses TaggedDocument to store reviews with a tag for further training. 

c) After loading all of this how many training examples are there? 

In [12]:
print(f"There are {len(unsup_sentences)} training examples are available in the unsup_sentences list.")

There are 175325 training examples are available in the unsup_sentences list.


d) Display the first 10 entries.

In [13]:
unsup_sentences[:10]

[TaggedDocument(words=['bromwell', 'high', 'is', 'a', 'cartoon', 'comedy', 'it', 'ran', 'at', 'the', 'same', 'time', 'as', 'some', 'other', 'programs', 'about', 'school', 'life', 'such', 'as', 'teachers', 'my', '35', 'years', 'in', 'the', 'teaching', 'profession', 'lead', 'me', 'to', 'believe', 'that', 'bromwell', 'hig', 'satire', 'is', 'much', 'closer', 'to', 'reality', 'than', 'is', 'teachers', 'the', 'scramble', 'to', 'survive', 'financially', 'the', 'insightful', 'students', 'who', 'can', 'see', 'right', 'through', 'their', 'pathetic', 'teachers', 'pomp', 'the', 'pettiness', 'of', 'the', 'whole', 'situation', 'all', 'remind', 'me', 'of', 'the', 'schools', 'i', 'knew', 'and', 'their', 'students', 'when', 'i', 'saw', 'the', 'episode', 'in', 'which', 'a', 'student', 'repeatedly', 'tried', 'to', 'burn', 'down', 'the', 'school', 'i', 'immediately', 'recalled', 'at', 'high', 'a', 'classic', 'line', 'inspector', 'here', 'to', 'sack', 'one', 'of', 'your', 'teachers', 'student', 'welcome', 

### Question 4

a) Shuffle the documents using the following code. 

In [14]:
import random
class PermuteSentences(object):
    def __init__(self, sents):
        self.sents = sents
        
    def __iter__(self):
        shuffled = list(self.sents)
        random.shuffle(shuffled)
        for sent in shuffled:
            yield sent

In [15]:
permuter = PermuteSentences(unsup_sentences)
model = Doc2Vec(permuter,dm=0,hs=1, vector_size=50)

2022-10-30 00:35:18,993 :INFO : collecting all words and their counts
2022-10-30 00:35:19,123 :INFO : PROGRESS: at example #0, processed 0 words (0/s), 0 word types, 0 tags
2022-10-30 00:35:19,396 :INFO : PROGRESS: at example #10000, processed 1436415 words (5269542/s), 45926 word types, 10000 tags
2022-10-30 00:35:19,671 :INFO : PROGRESS: at example #20000, processed 2834721 words (5093790/s), 62055 word types, 20000 tags
2022-10-30 00:35:20,515 :INFO : PROGRESS: at example #30000, processed 4246007 words (1673026/s), 73635 word types, 30000 tags
2022-10-30 00:35:20,819 :INFO : PROGRESS: at example #40000, processed 5668828 words (4693729/s), 83213 word types, 40000 tags
2022-10-30 00:35:21,106 :INFO : PROGRESS: at example #50000, processed 7093178 words (4983443/s), 91608 word types, 50000 tags
2022-10-30 00:35:21,363 :INFO : PROGRESS: at example #60000, processed 8493648 words (5454155/s), 99051 word types, 60000 tags
2022-10-30 00:35:21,644 :INFO : PROGRESS: at example #70000, proc

2022-10-30 00:36:00,531 :INFO : worker thread finished; awaiting finish of 0 more threads
2022-10-30 00:36:00,532 :INFO : EPOCH - 1 : training on 24777191 raw words (18806595 effective words) took 31.7s, 592414 effective words/s
2022-10-30 00:36:01,543 :INFO : EPOCH 2 - PROGRESS: at 2.40% examples, 458460 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:36:02,556 :INFO : EPOCH 2 - PROGRESS: at 5.61% examples, 528417 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:36:03,565 :INFO : EPOCH 2 - PROGRESS: at 8.67% examples, 542549 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:36:04,570 :INFO : EPOCH 2 - PROGRESS: at 12.04% examples, 566125 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:36:05,577 :INFO : EPOCH 2 - PROGRESS: at 15.42% examples, 580190 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:36:06,581 :INFO : EPOCH 2 - PROGRESS: at 18.70% examples, 587657 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:36:07,582 :INFO : EPOCH 2 - PROGRESS: at 22.20% examples, 598622 words/s, in_qsize 5, ou

2022-10-30 00:37:07,033 :INFO : EPOCH 4 - PROGRESS: at 26.30% examples, 819017 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:37:08,038 :INFO : EPOCH 4 - PROGRESS: at 31.07% examples, 831365 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:37:09,043 :INFO : EPOCH 4 - PROGRESS: at 35.98% examples, 842626 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:37:10,052 :INFO : EPOCH 4 - PROGRESS: at 40.85% examples, 851776 words/s, in_qsize 4, out_qsize 1
2022-10-30 00:37:11,053 :INFO : EPOCH 4 - PROGRESS: at 45.87% examples, 861635 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:37:12,063 :INFO : EPOCH 4 - PROGRESS: at 50.92% examples, 868221 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:37:13,065 :INFO : EPOCH 4 - PROGRESS: at 55.75% examples, 872721 words/s, in_qsize 6, out_qsize 0
2022-10-30 00:37:14,065 :INFO : EPOCH 4 - PROGRESS: at 60.63% examples, 876155 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:37:15,070 :INFO : EPOCH 4 - PROGRESS: at 65.62% examples, 880001 words/s, in_qsize 6, out_

2022-10-30 00:38:12,246 :INFO : EPOCH 7 - PROGRESS: at 36.64% examples, 853760 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:38:13,251 :INFO : EPOCH 7 - PROGRESS: at 41.54% examples, 861982 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:38:14,259 :INFO : EPOCH 7 - PROGRESS: at 45.85% examples, 856466 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:38:15,259 :INFO : EPOCH 7 - PROGRESS: at 50.85% examples, 862814 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:38:16,267 :INFO : EPOCH 7 - PROGRESS: at 55.70% examples, 866739 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:38:17,271 :INFO : EPOCH 7 - PROGRESS: at 60.79% examples, 873812 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:38:18,274 :INFO : EPOCH 7 - PROGRESS: at 65.57% examples, 876355 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:38:19,275 :INFO : EPOCH 7 - PROGRESS: at 70.11% examples, 875053 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:38:20,280 :INFO : EPOCH 7 - PROGRESS: at 75.01% examples, 877802 words/s, in_qsize 5, out_

2022-10-30 00:39:17,110 :INFO : EPOCH 10 - PROGRESS: at 44.27% examples, 924309 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:39:18,117 :INFO : EPOCH 10 - PROGRESS: at 49.41% examples, 928973 words/s, in_qsize 6, out_qsize 0
2022-10-30 00:39:19,124 :INFO : EPOCH 10 - PROGRESS: at 54.51% examples, 930206 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:39:20,131 :INFO : EPOCH 10 - PROGRESS: at 59.39% examples, 928076 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:39:21,139 :INFO : EPOCH 10 - PROGRESS: at 64.34% examples, 928318 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:39:22,157 :INFO : EPOCH 10 - PROGRESS: at 69.43% examples, 929480 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:39:23,169 :INFO : EPOCH 10 - PROGRESS: at 74.54% examples, 930385 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:39:24,172 :INFO : EPOCH 10 - PROGRESS: at 79.66% examples, 931623 words/s, in_qsize 5, out_qsize 0
2022-10-30 00:39:25,179 :INFO : EPOCH 10 - PROGRESS: at 84.51% examples, 929458 words/s, in_qsiz

b) Using the scikit learn docs, explain the function of the code in part (a)

Firstly, we create a class called PermuteSentences. The class allows us to pass in the object and turn it into a list, then we use the shuffle method from random to shuffle the list. We pass in the unsup_sentences (which stores all the reviews) as an object to the PermuteSentences and store them in a variable called permuter. From the scikit learn docs of Doc2Vec, the first parameter we need is the documents. Documents is a list of TaggedDocument that we want to pass in for training. In our case, is the shuffle unsup_sentences. The second parameter dm defines the training algorithm that we want to specify for this training. It allows 1 or 0 as input, where 1 indicates 'distributed memory' and 0 is distributed bag of words. The third parameter is hs, which is whether to use hierarchical softmax for training. It allows 0 or 1 as input, where 1 indicates hierarchical softmax will be used and 0 indicates negative sampling will be used. The last parameter size is equal to 50, which means the vector representing each document will contain 50 elements. The vector maps the document to a point in 50-dimensional space. Higher dimensions allow more differentiation between documents. 

c) Once the training is complete delete all but the inference data with the following code.

In [17]:
# done with training, free up some memory
model.delete_temporary_training_data(keep_inference=True)

AttributeError: 'Doc2Vec' object has no attribute 'delete_temporary_training_data'

d) At this point this is a solid model that can be used in a product. Save the model so that it can be loaded later with model = DocsVec.Load(‘reviews.d2v’)

In [19]:
model.save('reviews.d2v')

2022-10-30 11:07:18,490 :INFO : Doc2Vec lifecycle event {'fname_or_handle': 'reviews.d2v', 'separately': 'None', 'sep_limit': 10485760, 'ignore': frozenset(), 'datetime': '2022-10-30T11:07:18.490616', 'gensim': '4.0.1', 'python': '3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)]', 'platform': 'Windows-10-10.0.19041-SP0', 'event': 'saving'}
2022-10-30 11:07:18,505 :INFO : not storing attribute cum_table
2022-10-30 11:07:20,311 :INFO : saved reviews.d2v


### Question 5

a) Use model.infer, and the utility function to infer the vector for the phrase “This place is not worth your time, let alone Vegas.”

In [20]:
model.infer_vector(extract_words("This place is not worth your time, let alone Vegas."))

array([ 0.24580933,  0.00514891,  0.3595308 , -0.52849627,  0.36814606,
        0.38301033,  0.3920034 ,  0.03434087, -0.03278954, -0.2591965 ,
        0.2423288 ,  0.07339396, -0.00290345, -0.26203755, -0.13965148,
        0.02828451, -0.18127406, -0.2573375 , -0.19473793,  0.00873207,
       -0.10308146,  0.20605232,  0.07073209, -0.63871187, -0.37917265,
       -0.08233731,  0.21018082,  0.09837718,  0.6126511 , -0.03327044,
        0.6493887 , -0.17822012, -0.04948199,  0.06823016, -0.10996078,
        0.08465364,  0.20656943, -0.2342572 ,  0.16749963,  0.04028142,
       -0.04747786,  0.5186926 , -0.07909732, -0.16011365, -0.35905966,
        0.52198356, -0.37370095, -0.06028552, -0.3244094 , -0.1772991 ],
      dtype=float32)

b) Import cosine_similarity. Refer to the code snippet that follows.

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

c) Use cosine similarity to compare the following comments. <br>
> I. “this place is not worth your time, let alone Vegas.”<br>
   II. “service sucks.”<br>

In [23]:
cosine_similarity(
    [model.infer_vector(extract_words("this place is not worth your time, let alone Vegas."))],
    [model.infer_vector(extract_words("service sucks."))])

array([[0.5614059]], dtype=float32)

d) Use cosine similarity to compare the following comments.<br>
>I. “highly recommended.”<br>
II. “service sucks.”<br>

In [24]:
cosine_similarity(
    [model.infer_vector(extract_words("highly recommended."))],
    [model.infer_vector(extract_words("service sucks."))])

array([[0.30124742]], dtype=float32)

### Question 6

a) Use the following code to ready the data you will use. The Yelp, Amazon, and imdb comments are available online again at the UCI ML Repository page.

In [25]:
sentences = []
sentvecs = []
sentiments = []
for fname in ["yelp", "amazon_cells", "imdb"]: 
    with open("sentiment labelled sentences/%s_labelled.txt" % fname, encoding='UTF-8') as f:
        for i, line in enumerate(f):
            line_split = line.strip().split('\t')
            sentences.append(line_split[0])
            words = extract_words(line_split[0])
            sentvecs.append(model.infer_vector(words, steps=10)) # create a vector for this document
            sentiments.append(int(line_split[1]))
            
# shuffle sentences, sentvecs, sentiments together
combined = list(zip(sentences, sentvecs, sentiments))
random.shuffle(combined)
sentences, sentvecs, sentiments = zip(*combined)

b) Explain what the code in part (a) has done.

The code in part (a) first creates three empty lists (sentences, sentvecs, sentiments). The for loop opens all the txt files in the sentiment labelled sentences folder. For each line of the txt file, it includes a review and a sentiment (0 for negative and 1 for positive). The first line of the code inside the for loop split the review and the sentiment. The review will store in the sentences list. Then, we use the infer_vector method to create a vector for the review. The sentiment for each review will store in the sentiments list. After the for loop, we use the zip() function to merge and match the three lists (sentences, sentvecs, sentiments). Then we turn the combined list from a tuple to a list. After that, the shuffle method from random will be used the shuffle the combined list. In the end, we use zip() along with the unpacking operator * to separate the elements of each tuple into independent sequences (sentences, sentvecs, sentiments).

c) Import KNeighborsClassifier

In [26]:
from sklearn.neighbors import KNeighborsClassifier

d) Create an instance of KNeighborsClassifier with 9 neighbors.

In [27]:
clf = KNeighborsClassifier(n_neighbors=9)

e) Output the cross validated scores for the KNC. Use the following code.

In [28]:
from sklearn.model_selection import cross_val_score
import numpy as np

scores = cross_val_score(clf, sentvecs, sentiments, cv=5)
np.mean(scores), np.std(scores)

(0.7883333333333333, 0.015129074290546971)